# Generated by Django 5.1.3 on 2024-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_parent_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
